---
output:
  revealjs::revealjs_presentation:
    transition: slide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(dygraphs)
library(xts)
library(leaflet)
library(revealjs)
```

# Data Visualization {#title}

## Library of visualizations made in R

<center>

```{r, message = FALSE, warning=FALSE, echo=FALSE, fig.width=7, fig.height=6}
villa_icon <- makeIcon(iconUrl = "/Users/Wolfe/Desktop/Winter 2018/Data Visualization/Math 335/Case_Study_11/analysis/skull.png", iconWidth = 30, iconHeight = 40)


########################## Colors #################################
pench <- awesomeIcons(
  markerColor = "green"
)

oficina <- awesomeIcons(
  markerColor = "purple"
)

########################## Markers #################################

oficina_bao <- tibble(
  long = -58.569452,
  lat = -34.632637,
  label = "Mission Office"
)

villas <- tibble(
  long = c(-58.380879, -58.439433, -58.489639, -58.555165, -58.576406, -58.540030),
  lat = c(-34.584263, -34.649815, -34.689564, -34.591405, -34.624638, -34.620840),
  label = c("Villa 31", "Villa 1-11-14", "Villa Madero", "Villa Tropezon", "Villa Carlos Gardel", "La Fuerte Apache")
)

domocilios <- tibble(
  long = c(-58.719654),
  lat = c(-34.695099),
  label = c("Dario's house")
)

BAO_Data <- tibble(
  long = c(-58.738283, -58.767636, -58.539909, -58.677223, -59.113552, -58.728183, -60.018719, -60.021811),
  lat = c(-34.664863, -34.674616, -34.597635, -34.667288, -34.571306, -34.688278, -34.894501, -34.893411),
  label = c("Merlo 1 Pench", "Arco Iris Pench", "The Headquarters", "Ituzaingó Moldy Pench", "Lujan 1 Pench", "Parque House", "Bolivar Suite", "Chivilcoy Club")
)

########################## THE PLOT #################################

leaflet() %>% 
  setView(lng = -58.728, lat = -34.66, zoom = 8) %>% 
  addTiles() %>% 
  addAwesomeMarkers(data = BAO_Data, label = BAO_Data$label, icon = pench) %>% 
  addMarkers(data = domocilios, label = domocilios$label,
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "darkblue",
        "font-family" = "Titillium Web",
        "font-style" = "italic",
        "box-shadow" = "1px 1px rgba(0,0,0,0.25)",
        "font-size" = "15px",
        "border-color" = "rgba(0,0,0,0.5)"
      ))) %>% 
  addMarkers(data = villas, label = villas$label, icon = villa_icon,
    labelOptions = labelOptions(noHide = T, direction = "bottom",
      style = list(
        "color" = "black",
        "font-family" = "serif",
        "font-style" = "italic",
        "box-shadow" = "1px 1px rgba(0,0,0,0.25)",
        "font-size" = "15px",
        "border-color" = "rgba(0,0,0,0.5)"
      ))) %>% 
  addAwesomeMarkers(data = oficina_bao, label = oficina_bao$label, icon = oficina)
```

</center>





<style>
#title{
margin: auto;
text-align: center;
font-size: 60px;
margin-top: 3.5em;
color: #7F52E8;
}


</style>