---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

<p id="title">Machine Learning</p>

<br><br>

<center>
<p id = "note"><i>The following is not a full comprehension of my machine learning knowledge and experience, but rather a few select samples. Code for implementing several algorithms is found in the in the <strong>gridding</strong> link.</i></p>
</center>

<br><br>

<p id="method"><a id="method" class="method" href="cluster.html" target="_blank" >Clustering</a></p>

<br>

<center>
<ul id="list">
  <li id="desc">Used for grouping together elements based on attributes,   like TSA could look at the attributes of a person, and try to label       whether that person is a threat or not.</li>
</ul>
</center>

<br><br>

<p id="method"><a id="method" class="ensemble" href="ensemble_summary.html" target="_blank" >Algorithm Gridding</a></p>

<br>

<center>
<ul id="list">
  <li id="desc">Running one or many datasets through several algorithms in   order to see which one would predict best each dataset.</li>
</ul>
</center>

<br><br>

<p id="method"><a id="method" class="neural" href="neural.html" target="_blank" >Neural Network</a></p>

<br>

<center>
<ul id="list">
  <li id="desc">An algorithm that changes weights based on prediction error to best learn the attributes of a dataset, and therefore predict the best possible.</li>
</ul>
</center>


<br><br>

<p id="method"><a id="method" class="knn" href="knn.html" target="_blank" >KNN Regression</a></p>

<br>

<center>
<ul id="list">
  <li id="desc">A regression method where values are predicted for each row of a dataset based on calculated proximity to training set rows.</li>
</ul>
</center>


<br><br>

<p id="method"><a id="method" class="association" href="association.html" target="_blank" >Association Rule Mining</a></p>

<br>

<center>
<ul id="list">
  <li id="desc">Used for finding out which items are commonly grouped together, or leads to other items, which is very useful in analyzing shopping data.</li>
</ul>
</center>



<style>
@import url('https://fonts.googleapis.com/css?family=Bitter');
@import url('https://fonts.googleapis.com/css?family=Varela+Round');
@import url('https://fonts.googleapis.com/css?family=Roboto');
#title{
margin: auto;
text-align: center;
font-size: 85px;
color: #EECA38;
font-family: 'Bitter', serif;
letter-spacing: 5px;
}
#method{
margin: auto;
text-align: center;
font-size: 40px;
font-family: 'Quicksand', sans-serif;
}
.method{
color: #7F52E8;
}
.ensemble{
color: #183288;
}
.neural{
color: #195D1C;
}
.knn{
color: #E54A3B;
}
.association{
color: #5C2C2C;
}
#desc{
font-size: 20px;
font-family: 'Varela Round', sans-serif;
}
#list{
list-style-type: square;
margin-left: 3em;
margin-right: 3em;
}
#note{
font-size: 22px;
font-family: 'Roboto', sans-serif;
}
</style>

